<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.433">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2020-06-06">

<title>Analytical - Incertidumbre de una calibración no lineal</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="../../styles.css">
<link rel="stylesheet" href="../../custom.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title"><strong>Analytical</strong></span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html" rel="" target="">
 <span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../cursos.html" rel="" target="">
 <span class="menu-text">Cursos</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../blog.html" rel="" target="">
 <span class="menu-text">Blog</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../about.html" rel="" target="">
 <span class="menu-text">Quénes somos</span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools ms-auto tools-wide">
    <a href="https://github.com/analytical/website_analytical" rel="" title="Código fuente" class="quarto-navigation-tool px-1" aria-label="Código fuente"><i class="bi bi-github"></i></a>
    <a href="https://www.linkedin.com/in/cjgomezs/" rel="" title="" class="quarto-navigation-tool px-1" aria-label=""><i class="bi bi-linkedin"></i></a>
    <a href="mailto:cvgomez@gmail.com" rel="" title="" class="quarto-navigation-tool px-1" aria-label=""><i class="bi bi-envelope"></i></a>
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#métodos-de-estimación-de-incertidumbre-de-calibración" id="toc-métodos-de-estimación-de-incertidumbre-de-calibración" class="nav-link active" data-scroll-target="#métodos-de-estimación-de-incertidumbre-de-calibración">Métodos de estimación de incertidumbre de calibración</a></li>
  <li><a href="#datos-de-calibración" id="toc-datos-de-calibración" class="nav-link" data-scroll-target="#datos-de-calibración">Datos de calibración</a>
  <ul class="collapse">
  <li><a href="#estimación-de-incertidumbre-de-acuerdo-a-iso-8466-2" id="toc-estimación-de-incertidumbre-de-acuerdo-a-iso-8466-2" class="nav-link" data-scroll-target="#estimación-de-incertidumbre-de-acuerdo-a-iso-8466-2">Estimación de incertidumbre de acuerdo a ISO 8466-2</a></li>
  <li><a href="#estimación-de-incertidumbre-mediante-guía-iso-gum" id="toc-estimación-de-incertidumbre-mediante-guía-iso-gum" class="nav-link" data-scroll-target="#estimación-de-incertidumbre-mediante-guía-iso-gum">Estimación de incertidumbre mediante Guía ISO GUM</a></li>
  <li><a href="#estimación-con-el-método-de-monte-carlo" id="toc-estimación-con-el-método-de-monte-carlo" class="nav-link" data-scroll-target="#estimación-con-el-método-de-monte-carlo">Estimación con el Método de Monte Carlo</a></li>
  </ul></li>
  <li><a href="#bibliografía" id="toc-bibliografía" class="nav-link" data-scroll-target="#bibliografía">Bibliografía</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Incertidumbre de una calibración no lineal</h1>
<p class="subtitle lead">Método GUM y Monte Carlo – Norma ISO 8466:2</p>
</div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">June 6, 2020</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<p>En un <a href="https://www.analytical.cl/post/como-calcular-la-incertidumbre-de-una-curva-de-calibracion/">post anterior</a> revisamos cómo estimar la incertidumbre de la concentración de una muestra problema, cuando ésta ha sido obtenida interpolando la señal instrumental en una curva de calibración lineal.</p>
<p>La expresión es relativamente simple y vimos también cómo podemos implementarla en el lenguaje de programación <code>R</code> a través del package <code>chemCal</code>.</p>
<p>Sin embargo, la vida no es tan sencilla. Recoradará estimad@ lector@ que está bastante documentada la presencia de desviaciones de la linealidad a altas concentraciones, fenómeno muy conocido en los métodos espectrofotométricos (Ley de Lambert-Beer). La severidad de estas desviaciones varía en función del detector, el analito y otros factores físico-químicos del sistema de medición.</p>
<p>Cuando existen estas desviaciones y deseamos llevar a cabo un <a href="https://www.analytical.cl/post/como-demuestro-que-mi-curva-de-calibracion-es-lineal/">test de linealidad</a>, es muy probable que el test rechace el modelo lineal, por lo tanto, no podemos estimar la incertidumbre de calibración asumiendo este modelo. Si bien es cierto podemos reducir el rango lineal y diluir la muestra problema que está fuera del rango, la operación de dilución introduce nuevos errores (incluso errores humanos de transcripción bastante frecuentes).</p>
<p>Una alternativa válida sería utilizar un modelo de calibración que capture esta no linealidad evitando así la dilución de la muestra, por lo tanto el problema se reduce a:</p>
<blockquote class="blockquote">
<p>¿Cómo estimar la incertidumbre de una muestra problema que ha sido obtenida a través de una curva de calibración no lineal?</p>
</blockquote>
<p>Sin embargo, de esta pregunta se desprende al mismo tiempo otra interrogante:</p>
<blockquote class="blockquote">
<p>¿Cuál modelo de calibración no lineal utilizaré?</p>
</blockquote>
<p>Existen varios modelos de calibración no lineal:</p>
<ol type="1">
<li>Polinomios</li>
<li>New Rational (en realidad se llaman <em>aproximaciones de Padé</em>)</li>
<li>Splines</li>
<li>Loess</li>
<li>etc.</li>
</ol>
<p>Por lo tanto, no existe una respuesta completamente correcta desde la prespectiva estadística, pues un modelo cuadrático sería tan válido como un polinomio cúbico. Desde el punto de vista químico podríamos preguntarnos ¿qué sentido químico tiene una curva de calibración polinómica de grado 5? ¿Son interpretables los parámetros del modelo? En un modelo lineal como el de Lambert-Beer: <span class="math inline">\(y = \beta_{0} + \beta_{1}x\)</span> la pendiente de la curva de calibración tiene una interpretación química: es el producto entre coeficiente de extinción molar y la longitud de la celda:</p>
<p><span class="math display">\[
\underbrace{A}_\text{y} = \underbrace{\epsilon \cdot b}_\text{$\beta_{1}$} \cdot
\underbrace{C}_\text{x}
(\#eq:lambert)
\]</span> Pero recuerde este sabio consejo de un monstruo de la estadística aplicada:</p>
<blockquote class="blockquote">
<p><em>“All models are wrong, but some are useful”</em> – <cite>George Box</cite></p>
</blockquote>
<p>Por lo tanto, tenemos que tomar una decisión. Y obviamente, como soy el autor de este humilde post, ya la tomé por Ud. En este artículo estimaremos la incertidumbre de calibración de un modelo polinómico de grado 2, también conocido como modelo cuadrático.</p>
<p>Nota: Desde el punto de vista <strong>estrictamente estadístico</strong> los modelos polinómicos, como la calibración cuadrática, son también modelos lineales ya que los coeficientes del modelo son lineales</p>
<p><span class="math display">\[y = \beta_{0} + \beta_{1}x + \beta_{2}x^2 + \epsilon\]</span></p>
<p>En cambio, en un modelo del tipo exponencial:</p>
<p><span class="math display">\[y = \beta_{0}\cdot e^{\beta_{1}x}\]</span></p>
<p>El coeficiente <span class="math inline">\(\beta_{1}\)</span> no es una función lineal.</p>
<section id="métodos-de-estimación-de-incertidumbre-de-calibración" class="level1">
<h1>Métodos de estimación de incertidumbre de calibración</h1>
<p>En este post ejemplificaremos y compararemos tres métodos de estimación de incertidumbre de calibración:</p>
<ol type="1">
<li><p>Norma ISO 8466-2:2001 <em>Water quality – Calibration and evaluation of analytical methods and estimation of performance characteristics – Part 2: Calibration strategy for non-linear second-order calibration functions.</em></p></li>
<li><p>Método GUM</p></li>
<li><p>Método de Monte Carlo (Suplemento 1 ISO-GUM)</p></li>
</ol>
<p>Implementaremos todos los métodos en el lenguaje de programación <code>R</code>, explicando paso a paso el código fuente con el fin de que Ud. obtenga los mismos resultados, es decir, un <strong>análisis reproducible</strong>.</p>
</section>
<section id="datos-de-calibración" class="level1">
<h1>Datos de calibración</h1>
<p>Para ejemplificar los cálculos, utilizaremos los datos de calibración indicados en el ejemplo de la sección 7 de la norma ISO 8466-2. El siguiente código <code>R</code> nos permite ingresar los datos manualmente:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Ingresamos los datos de calibración de la sección 7 de la norma ISO 8466-2</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="co"># x: concentración en mg/L</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="co"># y: Absorbancia [UA]</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">12</span>, <span class="dv">18</span>, <span class="dv">24</span>, <span class="dv">30</span>, <span class="dv">36</span>, <span class="dv">42</span>, <span class="dv">48</span>, <span class="dv">54</span>, <span class="dv">60</span>, <span class="dv">66</span>)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">0.083</span>, <span class="fl">0.123</span>, <span class="fl">0.164</span>, <span class="fl">0.203</span>, <span class="fl">0.240</span>, <span class="fl">0.273</span>, <span class="fl">0.303</span>, <span class="fl">0.334</span>, <span class="fl">0.364</span>, <span class="fl">0.393</span>)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>d <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(x, y) <span class="co"># creamos un data frame con las variables x e y (esto es</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>                      <span class="co"># análogo a una matriz de datos en Excel con dos columnas)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>A continuación graficamos la curva de calibración con la librería <code>ggplot2</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2) <span class="co"># cargamos la librería ggplot2</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">theme_set</span>(<span class="fu">theme_minimal</span>()) <span class="co"># esto es sólo por una cuestión estética del gráfico</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(d, <span class="fu">aes</span>(<span class="at">x =</span> x, <span class="at">y =</span> y)) <span class="sc">+</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">'red'</span>) <span class="sc">+</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">'Concentración [mg/L]'</span>) <span class="sc">+</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">'Absorbancia [UA]'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-1-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Mmm… no sé Ud. pero yo veo una leve curvatura. Como lo vimos en un <a href="https://www.analytical.cl/post/como-demuestro-que-mi-curva-de-calibracion-es-lineal/">post anterior</a> llevaremos a cabo un análisis estadístico básico para evaluar si el modelo de calibración lineal es adecuado, o si nos inclinamos por la hipótesis de no linealidad.</p>
<p>Como no tenemos replicados de cada punto de calibración, haremos un Test de Linealidad de Mandel. Lo primero, es ajustar un modelo lineal a los datos <span class="math inline">\(y = a + bx\)</span>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>fit.lineal <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> x, <span class="at">data =</span> d) <span class="co"># ajustamos un modelo lineal y lo guardamos </span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>                                  <span class="co"># con el nombre fit.lineal</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit.lineal) <span class="co"># para ver el análisis estadístico del ajuste</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = y ~ x, data = d)

Residuals:
      Min        1Q    Median        3Q       Max 
-0.010636 -0.004720  0.001000  0.005727  0.009151 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 0.0250303  0.0058314   4.292  0.00264 ** 
x           0.0057172  0.0001368  41.803 1.18e-10 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.007453 on 8 degrees of freedom
Multiple R-squared:  0.9954,    Adjusted R-squared:  0.9949 
F-statistic:  1747 on 1 and 8 DF,  p-value: 1.181e-10</code></pre>
</div>
</div>
<p>Esta tabla nos dice que el intercepto del modelo es <span class="math inline">\(a = 0.0250303\)</span> y la pendiente <span class="math inline">\(b = 0.0057172\)</span>. Note el alto coeficiente de determinación <span class="math inline">\(r^{2} = 0.9954\)</span> lo cual indica que es un buen modelo. El coeficiente de correlación es <span class="math inline">\(r = 0.998\)</span> que si bien es un dato a considerar, no es una prueba formal de linealidad.</p>
<p>La siguiente figura muestra el ajuste lineal sobre los datos de calibración:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggpmisc) <span class="co"># para escribir ecuaciones dentro del gráfico</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: ggpp</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Registered S3 methods overwritten by 'ggpp':
  method                  from   
  heightDetails.titleGrob ggplot2
  widthDetails.titleGrob  ggplot2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'ggpp'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:ggplot2':

    annotate</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in .recacheSubclasses(def@className, def, env): undefined subclass
"ndiMatrix" of class "replValueSp"; definition not updated</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Registered S3 method overwritten by 'ggpmisc':
  method                  from   
  as.character.polynomial polynom</code></pre>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(d, <span class="fu">aes</span>(<span class="at">x =</span> x, <span class="at">y =</span> y)) <span class="sc">+</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">'red'</span>) <span class="sc">+</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">'lm'</span>, <span class="at">se =</span> F, </span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>              <span class="at">size =</span> <span class="fl">0.5</span>) <span class="sc">+</span> <span class="co"># dibuja la curva de calibración lineal</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">'Concentración [mg/L]'</span>) <span class="sc">+</span></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">'Absorbancia [UA]'</span>) <span class="sc">+</span></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_poly_eq</span>(<span class="fu">aes</span>(<span class="at">label =</span>  <span class="fu">paste</span>(<span class="fu">stat</span>(eq.label), <span class="fu">stat</span>(rr.label), </span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">sep =</span> <span class="st">"*</span><span class="sc">\"</span><span class="st">, </span><span class="sc">\"</span><span class="st">*"</span>)), </span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>               <span class="at">formula =</span> y <span class="sc">~</span> x, </span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>               <span class="at">parse =</span> <span class="cn">TRUE</span>, </span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>               <span class="at">rr.digits =</span> <span class="dv">4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.
ℹ Please use `linewidth` instead.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: `stat(eq.label)` was deprecated in ggplot2 3.4.0.
ℹ Please use `after_stat(eq.label)` instead.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/plot.lineal-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Se observa que el ajuste lineal no es un buen modelo, pues no captura la curvatura de los datos a pesar del alto coeficiente de correlación. Esto se oberva más claramente si obervamos el gráfico de residuos:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(fit.lineal, <span class="at">which =</span> <span class="dv">1</span>, <span class="at">add.smooth =</span> F, <span class="at">pch =</span> <span class="dv">19</span>, <span class="at">col =</span> <span class="st">'red'</span>, </span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">'Gráfico de residuos modelo lineal'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/fit.lin.res-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>La evidencia en contra del modelo lineal es abrumadora, el gráfico muestra claramente un patrón en los residuos que indica que el modelo lineal no es adecuado. Sin embargo, a pesar de la evidencia, haremos el Test de Mandel para “comprobar” esta hipótesis. Para aplicar el Test de Mandel debemos ahora ajustar el modelo cuadrático y compararlo con el modelo lineal. Para ser consistentes en la notación de la norma ISO 8466-2, definiremos el modelo de calibración cuadrático como:</p>
<p><span class="math display">\[
y = a + bx + cx^2
\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>fit.nolineal <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> x <span class="sc">+</span> <span class="fu">I</span>(x<span class="sc">^</span><span class="dv">2</span>), <span class="at">data =</span> d) <span class="co"># ajuste cuadrático y los guardamos </span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>                                          <span class="co"># con el nombre fit.nolineal</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit.nolineal)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = y ~ x + I(x^2), data = d)

Residuals:
       Min         1Q     Median         3Q        Max 
-1.864e-03 -1.114e-03  6.818e-05  9.432e-04  1.939e-03 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -5.621e-03  2.475e-03  -2.271   0.0574 .  
x            7.670e-03  1.420e-04  54.005 1.96e-10 ***
I(x^2)      -2.504e-05  1.787e-06 -14.010 2.23e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.001479 on 7 degrees of freedom
Multiple R-squared:  0.9998,    Adjusted R-squared:  0.9998 
F-statistic: 2.23e+04 on 2 and 7 DF,  p-value: 4.84e-14</code></pre>
</div>
</div>
<p>Se obtiene una tabla similar que la del modelo lineal, con la adición del coeficiente que acompaña al <span class="math inline">\(x^2\)</span>: <code>I(x^2)</code> <span class="math inline">\(= -2.504\times 10^{-5}\)</span>. Note que el coeficiente de determinación del modelo cuadrático es mayor que el del modelo lineal. Esto siempre se cumplirá, lo que hace el Test de Mandel es discernir si esta “mejora” en el modelo es “significativa”.</p>
<p>La siguiente figura muestra el ajuste no lineal, el cual captura mucho mejor la curvatura de los datos:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(d, <span class="fu">aes</span>(<span class="at">x =</span> x, <span class="at">y =</span> y)) <span class="sc">+</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">'red'</span>) <span class="sc">+</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">'lm'</span>,         <span class="co"># dibuja la curva de calibración no lineal</span></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>              <span class="at">se =</span> F, </span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>              <span class="at">formula =</span> y <span class="sc">~</span> x <span class="sc">+</span> <span class="fu">I</span>(x<span class="sc">^</span><span class="dv">2</span>), <span class="at">size =</span> <span class="fl">0.5</span>) <span class="sc">+</span> </span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">'Concentración [mg/L]'</span>) <span class="sc">+</span></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">'Absorbancia [UA]'</span>) <span class="sc">+</span></span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_poly_eq</span>(<span class="fu">aes</span>(<span class="at">label =</span>  <span class="fu">paste</span>(<span class="fu">stat</span>(eq.label), <span class="fu">stat</span>(rr.label), </span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">sep =</span> <span class="st">"*</span><span class="sc">\"</span><span class="st">, </span><span class="sc">\"</span><span class="st">*"</span>)),</span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a>               <span class="at">formula =</span> y <span class="sc">~</span> x <span class="sc">+</span> <span class="fu">I</span>(x<span class="sc">^</span><span class="dv">2</span>), </span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a>               <span class="at">parse =</span> <span class="cn">TRUE</span>, </span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a>               <span class="at">rr.digits =</span> <span class="dv">4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/plot.nolineal-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Ok, aplicamos el Test de Mandel con el comando <code>anova</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(fit.lineal, fit.nolineal)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: y ~ x
Model 2: y ~ x + I(x^2)
  Res.Df        RSS Df  Sum of Sq      F    Pr(&gt;F)    
1      8 0.00044442                                   
2      7 0.00001530  1 0.00042912 196.29 2.235e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>El p-value del test de Mandel es <span class="math inline">\(2.23\times 10^{-6}\)</span>, el cual de acuerdo a la interpretación tradicional, indica que el modelo lineal no es adecuado para los datos de calibración.</p>
<p>Procedamos, entonces, a estimar la incertidumbre de la concentración <span class="math inline">\(\hat{x}\)</span> de una muestra problema, cuyo valor fue obtenido interpolando la señal instrumental en el modelo de calibración no lineal.</p>
<section id="estimación-de-incertidumbre-de-acuerdo-a-iso-8466-2" class="level2">
<h2 class="anchored" data-anchor-id="estimación-de-incertidumbre-de-acuerdo-a-iso-8466-2">Estimación de incertidumbre de acuerdo a ISO 8466-2</h2>
<p>Desde el punto de vista metrológico, la aproximación que indica esta norma es similar a lo que dicta la guía ISO GUM clásica, es decir, estima la incertidumbre a partir de un modelo de medición <span class="math inline">\(y = f(x)\)</span>. La “gracia” de esta norma es que nos ahorra tinta, pues la ecuación de incertidumbre ya está “algebraicamente manipulada”. No entraremos en los detalles de las primeras secciones de la norma los cuales estudian el comportamiento de la curvatura, es decir, si será posible encontrar un máximo o un mínimo, lo cual es clave en la utilidad del modelo cuadrático como función de calibración. Esto es importante porque recuerde que una función parabólica tiene dos soluciones, si existiera un máximo o un mínimo en el rango de trabajo, el modelo cuadrático no puede ser utilizado como función de calibración.</p>
<p>La siguiente ecuación calcula la <strong>incertidumbre expandida</strong> <span class="math inline">\(I(\hat{x}) = U_{\hat{x}}\)</span> de la concentración de la muestra problema <span class="math inline">\(\hat{x}\)</span>, interpolada en la curva de calibración no lineal <span class="math inline">\(y = a + bx + cx^2\)</span>. Corresponde a la ecuación (27) de la norma:</p>
<p><span class="math display">\[
I(\hat{x}) = \frac{s_{y} \cdot t_{n - 3,\, 95\%}}{b + 2c\hat{x}} \cdot
            \sqrt{\frac{1}{N} + \frac{1}{\hat{N}} +
            \frac{(\hat{x} - \overline{x})^2 \, Q_{x^4} +
            \left(\hat{x}^2 - \frac{\sum x_{i}^{2}}{N} \right)^2 Q_{xx} -
            2(\hat{x} - \overline{x})
            \left(\hat{x}^2 - \frac{\sum x_{i}^{2}}{N} \right) Q_{x^3}}
            {Q_{x^4} Q_{xx} - \left( Q_{x^3} \right)^2}}
\]</span></p>
<p>donde:</p>
<p><span class="math display">\[
s_{y} = \sqrt{\frac{\sum (y_{i} -\hat{y})^2}{N - 3}}
\]</span></p>
<ul>
<li><p><span class="math inline">\(y_{i}\)</span> es la respuesta experimental observada del estándar <span class="math inline">\(i\)</span>, <span class="math inline">\(\hat{y}\)</span> es la respuesta instrumental que predice el modelo para el mismo estándar <span class="math inline">\(i\)</span>, por lo tanto <span class="math inline">\(e_{i} = y_{i} - \hat{y}\)</span> es el residuo. <span class="math inline">\(N\)</span> es el número de calibrantes. ¿Por qué el denominador es <span class="math inline">\(N - 3\)</span> y no <span class="math inline">\(N -2\)</span> como en la calibración lineal? Porque el modelo cuadrático posee tres parámetros <span class="math inline">\(a\)</span>, <span class="math inline">\(b\)</span> y <span class="math inline">\(c\)</span>.</p></li>
<li><p><span class="math inline">\(t_{N - 3,\, 95\%}\)</span> es el valor del T de Student con <span class="math inline">\(N - 3\)</span> grados de libertad y un 95% de confianza.</p></li>
<li><p><span class="math inline">\(\hat{N}\)</span> es el número de replicados independientes de la muestra problema. Como discutimos en <a href="https://www.analytical.cl/post/como-calcular-la-incertidumbre-de-una-curva-de-calibracion/">otro post</a>, esto no corresponde a inyectar <span class="math inline">\(\hat{N}\)</span> veces la misma muestra en el instrumento.</p></li>
<li><p><span class="math inline">\(\hat{x}\)</span> es la concentración de la muestra problema interpolada en la curva de calibración no lineal, la cual se obtiene resolviendo la ecuación cuadrática. Como Ud. recordará de sus años mozos esto siginifica que la concentración interpolada se obtiene a partir de:</p></li>
</ul>
<p><span class="math display">\[\hat{x} = \frac{-b \pm \sqrt{b^2 - 4(a - y_{0})c}}{2c}\]</span> donde <span class="math inline">\(y_{0}\)</span> es la señal instrumental de la muestra problema.</p>
<ul>
<li><p><span class="math inline">\(x_{i}\)</span> es la concentración del estándar <span class="math inline">\(i\)</span></p></li>
<li><p><span class="math inline">\(\overline{x} = \sum_{i = 1}^{N} x_{i}\)</span> es el promedio de las concentraciones de los calibrantes.</p></li>
</ul>
<p>Finalmente:</p>
<p><span class="math display">\[
\begin{aligned}
Q_{xx}  &amp;= \sum x_{i}^2 - \frac{\left(\sum x_{i}\right)^2}{N} \\
Q_{x^3} &amp;= \sum x_{i}^3 - \left(\sum x_{i} \times \frac{\sum x_{i}^2}{N}\right) \\
Q_{x^4} &amp;= \sum x_{i}^4 - \frac{\left(\sum x_{i}^2\right)^2}{N}
\end{aligned}
\]</span></p>
<p>Ok, nada del otro mundo. Es bien fea, pero sólo son operaciones de aritmética básica. Algunas observaciones:</p>
<p>Como Ud. recordará en el caso de la calibración lineal, a partir de esta ecuación podemos inferir que si deseamos minimizar la incertidumbre de calibración no lineal podemos :</p>
<ol type="1">
<li>Aumentar el número de calibrantes <span class="math inline">\(N\)</span></li>
<li>Aumentar el número de replicados independientes de la muestra problema <span class="math inline">\(\hat{N}\)</span></li>
<li>Aumentar la sensibilidad del método, que en el caso de la calibración cuadrática está dada por <span class="math inline">\(b + 2c\hat{x}\)</span>, es decir, depende de la concentración de la muestra problema <span class="math inline">\(\hat{x}\)</span>. En cambio, en la calibración lineal la sensibilidad era constante en todo el rango de concentración estudiado y correspondía a la pediente de la curva.</li>
</ol>
<p>En el caso de la calibración lineal, la incertidumbre de calibración se minimiza en el centroide de la curva, en el caso del modelo cuadrático esto no siempre es así. Observe en la siguiente figura las bandas de confianza de ambos tipos de calibración:</p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/patch-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Advierta que ambos modelos comparten la propiedad que la mayor incertidumbre se encuentra en los extremos. Sin embargo, en la calibración cuadrática, para este conjunto de datos, la menor incertidumbre no está en el centro de la curva.</p>
<p>Ok, a continuación implementaremos la ecuación de incertidumbre en <code>R</code> con los datos del ejemplo de la sección 7 de la norma. La señal instrumental de la muestra problema es <span class="math inline">\(y_{0} = 0.084\)</span> UA:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>N <span class="ot">&lt;-</span> <span class="fu">length</span>(x) <span class="co"># Número de calibrantes</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>N.hat <span class="ot">&lt;-</span> <span class="dv">1</span>     <span class="co"># Número de replicados de la muestra problema</span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>Qxx <span class="ot">&lt;-</span> <span class="fu">sum</span>(x<span class="sc">^</span><span class="dv">2</span>) <span class="sc">-</span> <span class="fu">sum</span>(x)<span class="sc">^</span><span class="dv">2</span><span class="sc">/</span>N</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>Qx3 <span class="ot">&lt;-</span> <span class="fu">sum</span>(x<span class="sc">^</span><span class="dv">3</span>) <span class="sc">-</span>(<span class="fu">sum</span>(x) <span class="sc">*</span> <span class="fu">sum</span>(x<span class="sc">^</span><span class="dv">2</span>)<span class="sc">/</span>N)</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>Qx4 <span class="ot">&lt;-</span> <span class="fu">sum</span>(x<span class="sc">^</span><span class="dv">4</span>) <span class="sc">-</span> <span class="fu">sum</span>(x<span class="sc">^</span><span class="dv">2</span>)<span class="sc">^</span><span class="dv">2</span><span class="sc">/</span>N</span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>a <span class="ot">&lt;-</span> fit.nolineal<span class="sc">$</span>coefficients[<span class="dv">1</span>]</span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>b <span class="ot">&lt;-</span> fit.nolineal<span class="sc">$</span>coefficients[<span class="dv">2</span>]</span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a>c <span class="ot">&lt;-</span> fit.nolineal<span class="sc">$</span>coefficients[<span class="dv">3</span>]</span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a>s.y <span class="ot">&lt;-</span> <span class="fu">summary</span>(fit.nolineal)<span class="sc">$</span>sigma <span class="co"># Es lo que R denomina Residual standard error</span></span>
<span id="cb23-12"><a href="#cb23-12" aria-hidden="true" tabindex="-1"></a>t <span class="ot">&lt;-</span> <span class="fu">qt</span>(<span class="fl">0.975</span>, N <span class="sc">-</span> <span class="dv">3</span>) <span class="co"># El T de Student (¡Ya no se usan tablas!)</span></span>
<span id="cb23-13"><a href="#cb23-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-14"><a href="#cb23-14" aria-hidden="true" tabindex="-1"></a>y0 <span class="ot">&lt;-</span> <span class="fl">0.084</span> <span class="co"># Es la señal instrumental de la muestra problema</span></span>
<span id="cb23-15"><a href="#cb23-15" aria-hidden="true" tabindex="-1"></a>x.hat <span class="ot">&lt;-</span> (<span class="sc">-</span>b <span class="sc">+</span> <span class="fu">sqrt</span>(b<span class="sc">^</span><span class="dv">2</span> <span class="sc">-</span> <span class="dv">4</span><span class="sc">*</span>(a <span class="sc">-</span> y0)<span class="sc">*</span>c))<span class="sc">/</span>(<span class="dv">2</span><span class="sc">*</span>c) <span class="co"># Concentración de la muestra</span></span>
<span id="cb23-16"><a href="#cb23-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-17"><a href="#cb23-17" aria-hidden="true" tabindex="-1"></a>Ix <span class="ot">&lt;-</span> (s.y <span class="sc">*</span> t)<span class="sc">/</span>(b <span class="sc">+</span> <span class="dv">2</span><span class="sc">*</span>c<span class="sc">*</span>x.hat) <span class="sc">*</span> <span class="fu">sqrt</span>(</span>
<span id="cb23-18"><a href="#cb23-18" aria-hidden="true" tabindex="-1"></a>  <span class="dv">1</span><span class="sc">/</span>N <span class="sc">+</span> <span class="dv">1</span><span class="sc">/</span>N.hat <span class="sc">+</span> ((x.hat <span class="sc">-</span> <span class="fu">mean</span>(x))<span class="sc">^</span><span class="dv">2</span><span class="sc">*</span>Qx4 <span class="sc">+</span> (x.hat<span class="sc">^</span><span class="dv">2</span> <span class="sc">-</span> <span class="fu">sum</span>(x<span class="sc">^</span><span class="dv">2</span>)<span class="sc">/</span>N)<span class="sc">^</span><span class="dv">2</span> <span class="sc">*</span> Qxx <span class="sc">-</span>  </span>
<span id="cb23-19"><a href="#cb23-19" aria-hidden="true" tabindex="-1"></a>  <span class="dv">2</span><span class="sc">*</span>(x.hat <span class="sc">-</span> <span class="fu">mean</span>(x))<span class="sc">*</span>(x.hat<span class="sc">^</span><span class="dv">2</span> <span class="sc">-</span> <span class="fu">sum</span>(x<span class="sc">^</span><span class="dv">2</span>)<span class="sc">/</span>N)<span class="sc">*</span>Qx3)<span class="sc">/</span></span>
<span id="cb23-20"><a href="#cb23-20" aria-hidden="true" tabindex="-1"></a>  (Qx4 <span class="sc">*</span> Qxx <span class="sc">-</span> Qx3<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb23-21"><a href="#cb23-21" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb23-22"><a href="#cb23-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-23"><a href="#cb23-23" aria-hidden="true" tabindex="-1"></a>Ix <span class="ot">&lt;-</span> <span class="fu">unname</span>(Ix) <span class="co"># Simplemente es para dejar sólo el número</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>La concentración de la muestra es <span class="math inline">\(\hat{x} = 12.17\)</span> mg/L. Al aplicar esta metodología obtenemos una incertidumbre expandida de <span class="math inline">\(I(\hat{x}) = 0.63\)</span> mg/L, es decir, exactamente la misma que la que indica la norma ISO. Note que si Ud. quisiera combinar esta incertidumbre de calibración con algún otro factor (p.ej: masa de la muestra, volumen de aforo, etc.) debe primero tansformarla en incertidumbre estándar, dividiéndola por el factor de cobertura <span class="math inline">\(k\)</span>, que en este caso corresponde al t Student con <span class="math inline">\(N - 3\)</span> grados de libertad al 95% de confianza (k = 2.36):</p>
<p><span class="math display">\[
u_{\hat{x}} = \frac{U_{\hat{x}}}{k} = 0.27\, \, \text{mg/L}
\]</span> Por lo tanto, si tuviéramos que informar el resultado de la concentración de la muestra interpolada en la curva de calibración no lineal informaríamos <span class="math inline">\(12.17 \pm 0.63\)</span> mg/L [<em>nota mental: mmmm… esto de las cifras significativas da para otro post, pero dejémoslo así por ahora. No olvidar borrar este comentario.</em>]</p>
<p>¿Cómo varía esta incertidumbre de calibración no lineal con la concentración de la muestra? La siguiente figura muestra esta variación:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="dv">12</span>, <span class="dv">66</span>, <span class="at">by =</span> <span class="dv">6</span>) <span class="co"># Rango de concentración</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>N <span class="ot">&lt;-</span> <span class="fu">length</span>(x)</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>N.hat <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>mu.x <span class="ot">&lt;-</span> <span class="fu">mean</span>(x) <span class="co"># promedio de las concentraciones de los calibrantes</span></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>sq.x <span class="ot">&lt;-</span> <span class="fu">sum</span>(x<span class="sc">^</span><span class="dv">2</span>) <span class="co"># suma de las concentraciones de los calibrantes al cuadrado</span></span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>Qxx <span class="ot">&lt;-</span> <span class="fu">sum</span>(x<span class="sc">^</span><span class="dv">2</span>) <span class="sc">-</span> <span class="fu">sum</span>(x)<span class="sc">^</span><span class="dv">2</span><span class="sc">/</span>N</span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>Qx3 <span class="ot">&lt;-</span> <span class="fu">sum</span>(x<span class="sc">^</span><span class="dv">3</span>) <span class="sc">-</span>(<span class="fu">sum</span>(x) <span class="sc">*</span> <span class="fu">sum</span>(x<span class="sc">^</span><span class="dv">2</span>)<span class="sc">/</span>N)</span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>Qx4 <span class="ot">&lt;-</span> <span class="fu">sum</span>(x<span class="sc">^</span><span class="dv">4</span>) <span class="sc">-</span> <span class="fu">sum</span>(x<span class="sc">^</span><span class="dv">2</span>)<span class="sc">^</span><span class="dv">2</span><span class="sc">/</span>N</span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a>t <span class="ot">&lt;-</span> <span class="fu">qt</span>(<span class="fl">0.975</span>, N <span class="sc">-</span> <span class="dv">3</span>)</span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Para graficar la incertidumbre vs concentración, primero debemos crear una</span></span>
<span id="cb24-12"><a href="#cb24-12" aria-hidden="true" tabindex="-1"></a><span class="co"># función que tome un X (una concentración) y calcule el Y (incertidumbre)</span></span>
<span id="cb24-13"><a href="#cb24-13" aria-hidden="true" tabindex="-1"></a>Ux <span class="ot">&lt;-</span> <span class="cf">function</span>(x) {</span>
<span id="cb24-14"><a href="#cb24-14" aria-hidden="true" tabindex="-1"></a>    U <span class="ot">&lt;-</span> s.y<span class="sc">*</span>t<span class="sc">/</span>(b <span class="sc">+</span> <span class="dv">2</span><span class="sc">*</span>c<span class="sc">*</span>x) <span class="sc">*</span> <span class="fu">sqrt</span>(</span>
<span id="cb24-15"><a href="#cb24-15" aria-hidden="true" tabindex="-1"></a>    <span class="dv">1</span><span class="sc">/</span>N <span class="sc">+</span> <span class="dv">1</span><span class="sc">/</span>N.hat <span class="sc">+</span> ((x <span class="sc">-</span> mu.x)<span class="sc">^</span><span class="dv">2</span><span class="sc">*</span>Qx4 <span class="sc">+</span> (x<span class="sc">^</span><span class="dv">2</span> <span class="sc">-</span> sq.x<span class="sc">/</span>N)<span class="sc">^</span><span class="dv">2</span> <span class="sc">*</span> Qxx <span class="sc">-</span>  </span>
<span id="cb24-16"><a href="#cb24-16" aria-hidden="true" tabindex="-1"></a>    <span class="dv">2</span><span class="sc">*</span>(x <span class="sc">-</span> mu.x)<span class="sc">*</span>(x<span class="sc">^</span><span class="dv">2</span> <span class="sc">-</span> sq.x<span class="sc">/</span>N)<span class="sc">*</span>Qx3)<span class="sc">/</span></span>
<span id="cb24-17"><a href="#cb24-17" aria-hidden="true" tabindex="-1"></a>    (Qx4 <span class="sc">*</span> Qxx <span class="sc">-</span> Qx3<span class="sc">^</span><span class="dv">2</span>))</span>
<span id="cb24-18"><a href="#cb24-18" aria-hidden="true" tabindex="-1"></a>    <span class="fu">return</span>(<span class="fu">unname</span>(U))</span>
<span id="cb24-19"><a href="#cb24-19" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb24-20"><a href="#cb24-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-21"><a href="#cb24-21" aria-hidden="true" tabindex="-1"></a><span class="co"># Graficamos concentración (X) vs Incertidumbre (Y)</span></span>
<span id="cb24-22"><a href="#cb24-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-23"><a href="#cb24-23" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(x, <span class="fu">Ux</span>(x), <span class="at">type =</span> <span class="st">'n'</span>,</span>
<span id="cb24-24"><a href="#cb24-24" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">'Concentración vs Incertidumbre de calibración'</span>,</span>
<span id="cb24-25"><a href="#cb24-25" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">'Concentración [mg/L]'</span>,</span>
<span id="cb24-26"><a href="#cb24-26" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">'Incertidumbre expandida [mg/L]'</span>)</span>
<span id="cb24-27"><a href="#cb24-27" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(<span class="fu">spline</span>(x, <span class="fu">Ux</span>(x)), <span class="at">col =</span> <span class="st">'red'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/u.vs.con-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Se aprecia que la incertidumbre aumenta con la concentración en una forma no constante para concentraciones mayores a 20 mg/L. Tal como mencionamos anteriormente, el mínimo no se encuentra en el centro del rango de concentración como ocurre con la calibración lineal. Para encontrar el valor exacto de concentración que minimiza la incertidumbre en este rango, usamos el comando <code>optimize</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Busca el mínimo de la función Ux en el intervalo de 12 a 66 mg/L</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">optimize</span>(Ux, <span class="at">interval =</span> <span class="fu">c</span>(<span class="dv">12</span>, <span class="dv">66</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$minimum
[1] 20.29164

$objective
[1] 0.5808116</code></pre>
</div>
</div>
<p>La concentración que minimiza la incertidumbre es 20.29 mg/L.</p>
<p>Muy entretenido, pero la vida es corta y debemos ser eficientes por lo tanto, para evitarnos el “tedio” de implementar la fórmula a mano, utilizaremos el package <code>investr</code> el cual calcula exactamente la incertidumbre de calibración de un gran número de modelos de calibración, entre ellos, los modelos cuadráticos:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># y0 es la señal de la muestra problema y0 = 0.084 UA</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(investr) <span class="co"># Cargamos la librería investr</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>x.hat <span class="ot">&lt;-</span> <span class="fu">invest</span>(fit.nolineal, <span class="at">data =</span> d, <span class="at">y0 =</span> y0, <span class="at">interval =</span> <span class="st">'Wald'</span>)</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>x.hat</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  estimate      lower      upper         se 
12.1672952 11.5400416 12.7945489  0.2652657 </code></pre>
</div>
</div>
<p>donde:</p>
<ul>
<li><code>estimate</code> es la concentración de la muestra problema</li>
<li><code>upper</code> es el extremo superior de la incertidumbre expandida <span class="math inline">\(I(\hat{x})\)</span></li>
<li><code>lower</code> es el extremo inferior de la incertidumbre expandida <span class="math inline">\(I(\hat{x})\)</span></li>
<li><code>se</code> es la incertidumbre estándar de calibración <span class="math inline">\(u_{\hat{x}}\)</span>, la cual es exactamente igual a la obtenida por la fórmula anterior <span class="math inline">\(u_{\hat{x}} = \frac{U_{\hat{x}}}{k} = 0.27\, \, \text{mg/L}\)</span></li>
</ul>
<p>Note que si quisiéramos obener <span class="math inline">\(I(\hat{x})\)</span> a partir de esta tabla, tendríamos que hacer la siguiente operación <span class="math inline">\(I(\hat{x}) =\)</span> <code>upper</code> - <code>estimate</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>x.hat<span class="sc">$</span>upper <span class="sc">-</span> x.hat<span class="sc">$</span>estimate</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.6272536</code></pre>
</div>
</div>
<p>No podemos usar el package <code>chemCal</code> que utilizamos en un <a href="https://www.analytical.cl/post/como-calcular-la-incertidumbre-de-una-curva-de-calibracion/">post anterior</a> para estimar la incertidumbre de calibración, porque este package sólo soporta calibraciones lineales.</p>
</section>
<section id="estimación-de-incertidumbre-mediante-guía-iso-gum" class="level2">
<h2 class="anchored" data-anchor-id="estimación-de-incertidumbre-mediante-guía-iso-gum">Estimación de incertidumbre mediante Guía ISO GUM</h2>
<p>Ya que la señal instrumental es una función de la concentración, entonces, podemos utilizar la aproximación ISO GUM clásica para estimar la incertidumbre de calibración. Por “clásica” me refiero a utilizar la aproximación de Taylor con las derivadas parciales. Esta guía dice lo siguiente:</p>
<ol type="1">
<li>Expresar el mensurando como una ecuación de medición a través de una relación funcional con las magnitudes de entrada. En este caso el mensurando es la concentración <span class="math inline">\(\hat{x}\)</span> cuya ecuación de medición es la solución de la ecuación cuadrática <span class="math inline">\(y_{0} = a + b\hat{x} + c\hat{x^2}\)</span> donde <span class="math inline">\(y_{0}\)</span> es la señal de la muestra problema:</li>
</ol>
<p><span class="math display">\[
\hat{x} = \frac{-b \pm \sqrt{b^2 - 4(a - y_{0})c}}{2c}
\]</span> 2. Identificación de las fuentes de incertidumbre. Al observar la ecuación de medición identificamos las siguientes fuentes de incertidumbre:</p>
<ul>
<li>Parámetros del modelo cuadrático: <span class="math inline">\(a\)</span>, <span class="math inline">\(b\)</span> y <span class="math inline">\(c\)</span></li>
<li>Señal instrumental de la muestra problema <span class="math inline">\(y_{0}\)</span></li>
</ul>
<ol start="3" type="1">
<li>Evaluación de las fuentes de incertidumbre:</li>
</ol>
<ul>
<li>Las incertidumbres estándar de los parámetros del modelo pueden ser obtenidas directamente del ajuste cuadrático <code>fit.nolineal</code>:</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># parámetros del modelo</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>a <span class="ot">&lt;-</span> fit.nolineal<span class="sc">$</span>coeff[<span class="dv">1</span>]</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>b <span class="ot">&lt;-</span> fit.nolineal<span class="sc">$</span>coeff[<span class="dv">2</span>]</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>c <span class="ot">&lt;-</span> fit.nolineal<span class="sc">$</span>coeff[<span class="dv">3</span>]</span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a><span class="co"># las incertidumbres estándar de a, b y c las obtenemos con la función summary</span></span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a>ua <span class="ot">&lt;-</span> <span class="fu">summary</span>(fit.nolineal)<span class="sc">$</span>coefficients[<span class="dv">1</span>, <span class="dv">2</span>]</span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a>ub <span class="ot">&lt;-</span> <span class="fu">summary</span>(fit.nolineal)<span class="sc">$</span>coefficients[<span class="dv">2</span>, <span class="dv">2</span>]</span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a>uc <span class="ot">&lt;-</span> <span class="fu">summary</span>(fit.nolineal)<span class="sc">$</span>coefficients[<span class="dv">3</span>, <span class="dv">2</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li>La incertidumbre estándar de la señal instrumental de la muestra problema también puede obtenerse del ajuste cuadrático y corresponde a la desviación estándar residual:</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>uy0 <span class="ot">&lt;-</span> <span class="fu">summary</span>(fit.nolineal)<span class="sc">$</span>sigma</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>y0 <span class="ot">&lt;-</span> <span class="fl">0.084</span> <span class="co"># dato del problema, es decir, la absorbancia de la muestra</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ol start="4" type="1">
<li>Determinación de la incertidumbre estándar combinada <span class="math inline">\(u_{\hat{x}}\)</span> a través de la expresión:</li>
</ol>
<p><span class="math display">\[
u_{\hat{x}}^2 = \left( \frac{\partial{\hat{x}}}{\partial{y_{0}}}\right) ^{2} (u_{y_{0}})^{2} +
\left( \frac{\partial{\hat{x}}}{\partial{a}}\right) ^{2} (u_{a})^{2} +
\left( \frac{\partial{\hat{x}}}{\partial{b}}\right) ^{2} (u_{b})^{2} +
\left( \frac{\partial{\hat{x}}}{\partial{c}}\right )^{2} (u_{c})^{2}
\]</span></p>
<p>“sólo” nos falta obtener las derivadas parciales (aguante ese código <span class="math inline">\(\LaTeX\)</span>):</p>
<p><span class="math display">\[
\begin{aligned}
\frac{\partial{\hat{x}}}{\partial{y_{0}}} &amp;=
\frac{1}{\sqrt{b^{2} - 4c(a-y_{0})}} \\
\frac{\partial{\hat{x}}}{\partial{a}} &amp;=
  \frac{-1}{\sqrt{b^{2} - 4c(a-y_{0})}} \\
\frac{\partial{\hat{x}}}{\partial{b}} &amp;=
\frac{-1 + \frac{b}{\sqrt{b^{2} - 4c(a-y_{0})}}}{2c} \\
\frac{\partial{\hat{x}}}{\partial{c}} &amp;=
  \frac{-a + y_{0}}{c\sqrt{b^{2} - 4c(a-y_{0})}} -
  \frac{-b + \sqrt{b^{2} - 4c(a-y_{0})}}{2c^{2}}
\end{aligned}
\]</span></p>
<p>¡Listo! ahora debemos evaluar las expresiones. Pero como soy flojo, prefiero usar el excelente package <code>metRology</code> que hará todo el trabajo por mí:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(metRology) <span class="co"># cargamos la librería</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'metRology'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:base':

    cbind, rbind</code></pre>
</div>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>expr <span class="ot">&lt;-</span> <span class="fu">expression</span>((<span class="sc">-</span>b <span class="sc">+</span> <span class="fu">sqrt</span>(b<span class="sc">^</span><span class="dv">2</span> <span class="sc">-</span> <span class="dv">4</span><span class="sc">*</span>(a <span class="sc">-</span> y0)<span class="sc">*</span>c))<span class="sc">/</span>(<span class="dv">2</span><span class="sc">*</span>c)) <span class="co"># ecuación de medición</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">list</span>(<span class="at">a =</span> a, <span class="at">b =</span> b, <span class="at">c =</span> c, <span class="at">y0 =</span> y0) <span class="co"># valores de cada X input</span></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>u <span class="ot">&lt;-</span> <span class="fu">c</span>(ua, ub, uc, uy0) <span class="co"># incertidumbres estándar de cada X input</span></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>u.GUM <span class="ot">&lt;-</span> <span class="fu">uncert</span>(expr, x, u, <span class="at">method =</span> <span class="st">'GUM'</span>) <span class="co"># Usamos el método GUM</span></span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>u.GUM</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Uncertainty evaluation

Call:
  uncert.expression(obj = expr, x = x, u = u, method = "GUM")

Expression: (-b + sqrt(b^2 - 4 * (a - y0) * c))/(2 * c)

Evaluation method:  GUM 

Uncertainty budget:
   x             u            c           u.c        
a  -5.621212e-03 2.474778e-03   -141.6217 -0.35048212
b   7.670455e-03 1.420320e-04  -1723.1492 -0.24474238
c  -2.504209e-05 1.787394e-06 -20966.0252 -0.03747454
y0  8.400000e-02 1.478563e-03    141.6217  0.20939648

   y:  12.16727
u(y):  0.4774807 </code></pre>
</div>
</div>
<p>¿What? ¿Por qué obtuvimos una incertidumbre estándar de 0.477 y no la que calculamos con la ecuación de la norma ISO 0.265? Por la sencilla razón de que los parámetros de un modelo cuadrático no son independientes, sus covarianzas no son 0. Es más, algunas de las covarianzas son negativas. Observe la siguiente figura que fue obtenida simulando curvas de calibración cuadráticas. En la figura se muestra las correlaciones entre los tres parámetros del modelo no lineal:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Simularemos p = 200 curvas de calibración cuadráticas a partir de los datos </span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="co"># empíricos </span></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="dv">200</span> <span class="co"># Número de simulaciones</span></span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>a.sim <span class="ot">&lt;-</span> <span class="fu">numeric</span>(p) <span class="co"># vector que guardará el parámetro a</span></span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a>b.sim <span class="ot">&lt;-</span> <span class="fu">numeric</span>(p) <span class="co"># vector que guardará el parámetro b</span></span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a>c.sim <span class="ot">&lt;-</span> <span class="fu">numeric</span>(p) <span class="co"># vector que guardará el parámetro c</span></span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-9"><a href="#cb38-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Hacemos un loop</span></span>
<span id="cb38-10"><a href="#cb38-10" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>p){</span>
<span id="cb38-11"><a href="#cb38-11" aria-hidden="true" tabindex="-1"></a>  x.sim <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="dv">12</span>, <span class="dv">66</span>, <span class="at">by =</span> <span class="dv">6</span>)</span>
<span id="cb38-12"><a href="#cb38-12" aria-hidden="true" tabindex="-1"></a>  y.sim <span class="ot">&lt;-</span> a <span class="sc">+</span> b<span class="sc">*</span>x.sim <span class="sc">+</span> c<span class="sc">*</span>x.sim<span class="sc">^</span><span class="dv">2</span> <span class="sc">+</span> <span class="fu">rnorm</span>(<span class="fu">length</span>(x.sim), <span class="dv">0</span>, uy0)</span>
<span id="cb38-13"><a href="#cb38-13" aria-hidden="true" tabindex="-1"></a>  fit.nolineal.sim <span class="ot">&lt;-</span> <span class="fu">lm</span>(y.sim <span class="sc">~</span> x.sim <span class="sc">+</span> <span class="fu">I</span>(x.sim<span class="sc">^</span><span class="dv">2</span>))</span>
<span id="cb38-14"><a href="#cb38-14" aria-hidden="true" tabindex="-1"></a>  a.sim[i] <span class="ot">&lt;-</span> fit.nolineal.sim<span class="sc">$</span>coeff[<span class="dv">1</span>]</span>
<span id="cb38-15"><a href="#cb38-15" aria-hidden="true" tabindex="-1"></a>  b.sim[i] <span class="ot">&lt;-</span> fit.nolineal.sim<span class="sc">$</span>coeff[<span class="dv">2</span>]</span>
<span id="cb38-16"><a href="#cb38-16" aria-hidden="true" tabindex="-1"></a>  c.sim[i] <span class="ot">&lt;-</span> fit.nolineal.sim<span class="sc">$</span>coeff[<span class="dv">3</span>]</span>
<span id="cb38-17"><a href="#cb38-17" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb38-18"><a href="#cb38-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-19"><a href="#cb38-19" aria-hidden="true" tabindex="-1"></a><span class="co"># guardamos los parámetros simulados en un data frame que llamamos param.sim</span></span>
<span id="cb38-20"><a href="#cb38-20" aria-hidden="true" tabindex="-1"></a>param.sim <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(a.sim, b.sim, c.sim) </span>
<span id="cb38-21"><a href="#cb38-21" aria-hidden="true" tabindex="-1"></a>                                                </span>
<span id="cb38-22"><a href="#cb38-22" aria-hidden="true" tabindex="-1"></a><span class="co"># graficamos los parámetros simulados</span></span>
<span id="cb38-23"><a href="#cb38-23" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(param.sim)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Se advierte claramente que existe una correlación negativa entre los parámetros <span class="math inline">\(a\)</span> y <span class="math inline">\(b\)</span>, además entre <span class="math inline">\(b\)</span> y <span class="math inline">\(c\)</span>. La correlación entre <span class="math inline">\(a\)</span> y <span class="math inline">\(c\)</span> es positiva. En rigor, habría que incorporar las derivadas parciales cruzadas y las covarianzas entre los parámetros. De sólo pensarlo, me dan ganas de procastinar aún más la escritura de este post, así que recurriremos al package <code>metRology</code>.</p>
<p>La parte “fácil” es obtener la matriz de covarianzas de los parámetros del modelo con el comando <code>vcov</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>v <span class="ot">&lt;-</span> <span class="fu">vcov</span>(fit.nolineal)</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(v) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">'a'</span>, <span class="st">'b'</span>, <span class="st">'c'</span>) <span class="co"># solo cosmética para que aparezcan los nombres</span></span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a><span class="fu">rownames</span>(v) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">'a'</span>, <span class="st">'b'</span>, <span class="st">'c'</span>) <span class="co"># de los parámetros (es opcional)</span></span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>v</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>              a             b             c
a  6.124524e-06 -3.337187e-07  3.910406e-09
b -3.337187e-07  2.017310e-08 -2.491926e-10
c  3.910406e-09 -2.491926e-10  3.194776e-12</code></pre>
</div>
</div>
<p>La diagonal de esta matriz es precisamente la incertidumbre estándar al cuadrado de los parámetros (a.k.a sus varianzas). Si queremos, también podemos expresarla como matriz de correlaciones con el comando <code>cov2cor</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>param.cor <span class="ot">&lt;-</span> <span class="fu">cov2cor</span>(v)</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>param.cor</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           a          b          c
a  1.0000000 -0.9494193  0.8840269
b -0.9494193  1.0000000 -0.9815865
c  0.8840269 -0.9815865  1.0000000</code></pre>
</div>
</div>
<p>En la diagonal de esta matriz obviamente esperamos correlación 1. Se observa claramente la alta correlación entre los parámetros, como dijimos anteriormente, algunas de ellas son negativas.</p>
<p>La parte “difícil” es que debemos incorporar la variable señal instrumental de la muestra problema <span class="math inline">\(y_{0}\)</span>, la cual obviamente es independiente de los parámetros del modelo:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Incorporamos la variable y0 que es independiente de los parámetros</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>v <span class="ot">&lt;-</span> <span class="fu">rbind</span>(v, <span class="at">y0 =</span> <span class="fu">rep</span>(<span class="dv">0</span>, <span class="dv">3</span>)) </span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>v <span class="ot">&lt;-</span> <span class="fu">cbind</span>(v, <span class="at">y0 =</span> <span class="fu">rep</span>(<span class="dv">0</span>, <span class="dv">4</span>))</span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>v[<span class="dv">4</span>, <span class="dv">4</span>] <span class="ot">&lt;-</span> uy0<span class="sc">^</span><span class="dv">2</span> <span class="co"># Asignamos al elemento de la 4a fila y 4a columna  </span></span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a>                 <span class="co"># la varianza de y0</span></span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a>v</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>               a             b             c           y0
a   6.124524e-06 -3.337187e-07  3.910406e-09 0.000000e+00
b  -3.337187e-07  2.017310e-08 -2.491926e-10 0.000000e+00
c   3.910406e-09 -2.491926e-10  3.194776e-12 0.000000e+00
y0  0.000000e+00  0.000000e+00  0.000000e+00 2.186147e-06</code></pre>
</div>
</div>
<p>Ahora, incorporamos las covarianzas en el cálculo por método GUM:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>u.GUM.cov <span class="ot">&lt;-</span> <span class="fu">uncert</span>(expr, x, <span class="at">cov =</span> v, <span class="at">method =</span> <span class="st">"GUM"</span>)</span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>u.GUM.cov</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Uncertainty evaluation

Call:
  uncert.expression(obj = expr, x = x, method = "GUM", cov = v)

Expression: (-b + sqrt(b^2 - 4 * (a - y0) * c))/(2 * c)

Evaluation method:  GUM 

Uncertainty budget:
   x             u            c           u.c        
a  -5.621212e-03 2.474778e-03   -141.6217 -0.35048212
b   7.670455e-03 1.420320e-04  -1723.1492 -0.24474238
c  -2.504209e-05 1.787394e-06 -20966.0252 -0.03747454
y0  8.400000e-02 1.478563e-03    141.6217  0.20939648

   y:  12.16727
u(y):  0.2651904 </code></pre>
</div>
</div>
<p>¡Perfecto!, ahora sí, al incluir las covarianzas obtenemos resultados consistentes con el método descrito en la norma ISO 8466-2.</p>
</section>
<section id="estimación-con-el-método-de-monte-carlo" class="level2">
<h2 class="anchored" data-anchor-id="estimación-con-el-método-de-monte-carlo">Estimación con el Método de Monte Carlo</h2>
<p>No detallaremos aquí cómo funciona el método de Monte Carlo, puede consultarlo en <a href="https://www.analytical.cl/post/validacion-calculos-incertidumbre-quimica-analitica-metodo-monte-carlo/">este post</a> y en <a href="https://www.analytical.cl/post/validacion-calculos-incertidumbre-quimica-analitica-metodo-monte-carlo-parte2/">este otro</a>.</p>
<p>Sería super simple si usamos el package <code>metRology</code>, el problema es que el package lanza un error numérico cuando existen covarianzas negativas. Probé el ejemplo que incluye el manual de <code>metRology</code> y el error se repite. Es un problema al evaluar la suma de las correlaciones. Le consulté al autor Steve Ellison, sin embargo, a la fecha (09 de junio 2020) aún no tengo respuesta, a pesar de que Steve siempre responde las consultas en forma muy expedita. Otros usuarios han tenido un problema similar y se ha abierto un hilo en <a href="https://stackoverflow.com/questions/60971950/error-in-eigensigma-symmetric-true-0-x-0-matrix-in-metrology-uncertmc-wit/62119518#62119518">stackoverflow</a>.</p>
<p>Por lo tanto, implementamos el método de Monte Carlo “a mano” utilizando el package <code>MASS</code> el cual permite generar muestras aleatorias multivariadas incluyendo las correlaciones:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="co"># No funciona metRology MC así que lo hicimos a mano</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MASS) <span class="co"># cargamos la librería</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'MASS'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:patchwork':

    area</code></pre>
</div>
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Generamos n muestras aleatorias multivariadas, cuyas medias </span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a><span class="co"># corresponden a los valores de a, b, c e y0</span></span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a><span class="co"># La matriz de covarianza Sigma = v la calculamos anteriormente</span></span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>) <span class="co"># Para que Ud. obtenga los mismos resultados</span></span>
<span id="cb50-6"><a href="#cb50-6" aria-hidden="true" tabindex="-1"></a>muestra.MC <span class="ot">&lt;-</span> <span class="fu">mvrnorm</span>(<span class="at">n =</span> <span class="dv">10000</span>, <span class="at">mu =</span> <span class="fu">c</span>(a, b, c, y0), <span class="at">Sigma =</span> v, <span class="at">empirical =</span> T)</span>
<span id="cb50-7"><a href="#cb50-7" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(muestra.MC) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">'a'</span>, <span class="st">'b'</span>, <span class="st">'c'</span>, <span class="st">'y0'</span>) <span class="co"># solo cosmética</span></span>
<span id="cb50-8"><a href="#cb50-8" aria-hidden="true" tabindex="-1"></a>muestra.MC <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(muestra.MC) <span class="co"># lo guardamos como data.frame</span></span>
<span id="cb50-9"><a href="#cb50-9" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(muestra.MC) <span class="co"># muestra las primeras n = 6 simulaciones</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             a           b             c         y0
1 -0.006371785 0.007697494 -2.535336e-05 0.08771566
2 -0.006657346 0.007727893 -2.572028e-05 0.08385741
3 -0.005338584 0.007654631 -2.437727e-05 0.08643112
4 -0.006478276 0.007654191 -2.412670e-05 0.08417975
5 -0.008126340 0.007832532 -2.697179e-05 0.08478106
6 -0.005139204 0.007672558 -2.484339e-05 0.08644533</code></pre>
</div>
</div>
<p>Cada fila es una simulación. Si, por ejemplo, calculamos el promedio de cada variable simulada, obtenemos un valor similar a los valores empíricos. A mayor número de simulaciones, más nos acercamos a valores que asumimos como verdaderos.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">apply</span>(muestra.MC, <span class="dv">2</span>, mean) <span class="co"># promedio de cada columna</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            a             b             c            y0 
-5.621212e-03  7.670455e-03 -2.504209e-05  8.400000e-02 </code></pre>
</div>
</div>
<p>Bien, lo que tenemos que hacer es que en cada simulación debemos calcular la concentración de la muestra:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="co"># cargaré estas librerías sólo para facilitar la manipulación de los datos</span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(magrittr)</span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.4
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ lubridate 1.9.3     ✔ tibble    3.2.1
✔ purrr     1.0.2     ✔ tidyr     1.3.0
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ ggpp::annotate()   masks ggplot2::annotate()
✖ tidyr::extract()   masks magrittr::extract()
✖ dplyr::filter()    masks stats::filter()
✖ dplyr::lag()       masks stats::lag()
✖ dplyr::select()    masks MASS::select()
✖ purrr::set_names() masks magrittr::set_names()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Creamos una nueva variable llamada x.hat que corresponde a la concentración de</span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a><span class="co"># la muestra</span></span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a>muestra.MC <span class="ot">&lt;-</span> muestra.MC <span class="sc">%&gt;%</span> </span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">x.hat =</span> (<span class="sc">-</span>b <span class="sc">+</span> <span class="fu">sqrt</span>(b<span class="sc">^</span><span class="dv">2</span> <span class="sc">-</span> <span class="dv">4</span><span class="sc">*</span>(a <span class="sc">-</span> y0)<span class="sc">*</span>c))<span class="sc">/</span>(<span class="dv">2</span><span class="sc">*</span>c))</span>
<span id="cb56-5"><a href="#cb56-5" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(muestra.MC) <span class="co"># muestra las primeras n = 6 simulaciones</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             a           b             c         y0    x.hat
1 -0.006371785 0.007697494 -2.535336e-05 0.08771566 12.75935
2 -0.006657346 0.007727893 -2.572028e-05 0.08385741 12.20883
3 -0.005338584 0.007654631 -2.437727e-05 0.08643112 12.48521
4 -0.006478276 0.007654191 -2.412670e-05 0.08417975 12.32289
5 -0.008126340 0.007832532 -2.697179e-05 0.08478106 12.39039
6 -0.005139204 0.007672558 -2.484339e-05 0.08644533 12.43752</code></pre>
</div>
</div>
<p>La última columna corresponde a la concentración calculada para cada simulación. Por lo tanto, si queremos obtener la incertidumbre estándar de la concentración, basta calcular la desviación estándar de esa columna:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a>mu.x.hat.MC <span class="ot">&lt;-</span> <span class="fu">mean</span>(muestra.MC<span class="sc">$</span>x.hat) <span class="co"># valor promedio de concentración</span></span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>u.x.hat.MC <span class="ot">&lt;-</span> <span class="fu">sd</span>(muestra.MC<span class="sc">$</span>x.hat) <span class="co"># incertidumbre estándar de la concentración</span></span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a>u.x.hat.MC</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.265344</code></pre>
</div>
</div>
<p>Se obtiene una incertidumbre estándar de calibración de 0.265 mg/L, la cual es consistente con los otros métodos estudiados. La siguiente figura muestra el histograma de las concentraciones simuladas:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(muestra.MC<span class="sc">$</span>x.hat, </span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">breaks =</span> <span class="dv">20</span>,</span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">'Concentraciones simuladas por Monte Carlo'</span>,</span>
<span id="cb60-4"><a href="#cb60-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">'Concentración [mg/L]'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/plot.u.MC-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Finalmente, la siguiente tabla resume los resultados de los tres métodos considerando la incertidumbre estándar de calibración:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>tabla <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(Ix<span class="sc">/</span>t, u.GUM<span class="sc">$</span>u.y, u.GUM.cov<span class="sc">$</span>u.y, u.x.hat.MC)</span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(tabla, </span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">rownames =</span> <span class="cn">NA</span>,</span>
<span id="cb61-4"><a href="#cb61-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">'ISO'</span>, <span class="st">'GUM'</span>, <span class="st">'GUM/Covarianzas'</span>, <span class="st">'Monte Carlo'</span>),</span>
<span id="cb61-5"><a href="#cb61-5" aria-hidden="true" tabindex="-1"></a>             <span class="at">align =</span> <span class="st">'l'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">ISO</th>
<th style="text-align: left;">GUM</th>
<th style="text-align: left;">GUM/Covarianzas</th>
<th style="text-align: left;">Monte Carlo</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">0.2651904</td>
<td style="text-align: left;">0.4774807</td>
<td style="text-align: left;">0.2651904</td>
<td style="text-align: left;">0.265344</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Se aprecia claramente una excelente concordancia entre los tres métodos. Sin embargo, para que el método GUM entregue resultados correctos, es necesario incorporar las covarianzas entre las variables input.</p>
<p>En un próximo post exploraremos el método <em>Bootstrap</em>, un método estadístico por excelencia para estimar incertidumbre sin utilizar un modelo de medición…</p>
<blockquote class="blockquote">
<p>¡Dejad que los datos hablen!</p>
</blockquote>
</section>
</section>
<section id="bibliografía" class="level1">
<h1>Bibliografía</h1>
<ol type="1">
<li><p>Norma ISO 8466-2:2001 <em>Water quality – Calibration and evaluation of analytical methods and estimation of performance characteristics – Part 2: Calibration strategy for non-linear second-order calibration functions.</em></p></li>
<li><p>Brandon M. Greenwell and Christine M. Schubert Kabban (2014). investr: An R Package for Inverse Estimation. The R Journal, 6(1), 90-100. URL http://journal.r-project.org/archive/2014-1/greenwell-kabban.pdf.</p></li>
<li><p>NIST/SEMATECH e-Handbook of Statistical Methods, <em>Uncertainty for quadratic calibration using propagation of error</em>, https://www.itl.nist.gov/div898/handbook/mpc/section3/mpc3671.htm, 09 de junio 2020.</p></li>
<li><p>Nonlinear multivariate calibration methods in analytical chemistry Sonja Sekulic, Mary Beth Seasholtz, Ziyi Wang, Bruce R. Kowalski, Samuel E. Lee, and Bradley R. Holt <em>Analytical Chemistry 1993 65 (19), 835A-845A</em></p></li>
</ol>


</section>

<a onclick="window.scrollTo(0, 0); return false;" role="button" id="quarto-back-to-top"><i class="bi bi-arrow-up"></i> Back to top</a></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">Copyright 2024, Carlos Gómez</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/analytical/website_analytical">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/cjgomezs/">
      <i class="bi bi-linkedin" role="img">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>



</body></html>