<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.433">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2017-08-23">

<title>Analytical - ¿Cómo demuestro que mi curva de calibración es lineal?</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-KT9C16VQJX"></script>

<script type="text/javascript">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-KT9C16VQJX', { 'anonymize_ip': true});
</script>

<script src="../../site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="../../site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="../../styles.css">
<link rel="stylesheet" href="../../custom.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title"><strong>Analytical</strong></span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html" rel="" target="">
 <span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../cursos.html" rel="" target="">
 <span class="menu-text">Cursos</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../blog.html" rel="" target="">
 <span class="menu-text">Blog</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../libro.html" rel="" target="">
 <span class="menu-text">Libro</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../about.html" rel="" target="">
 <span class="menu-text">Quiénes somos</span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools ms-auto tools-wide">
    <a href="https://github.com/analytical/website_analytical" rel="" title="Código fuente" class="quarto-navigation-tool px-1" aria-label="Código fuente"><i class="bi bi-github"></i></a>
    <a href="https://www.linkedin.com/in/cjgomezs/" rel="" title="" class="quarto-navigation-tool px-1" aria-label=""><i class="bi bi-linkedin"></i></a>
    <a href="mailto:cvgomez@gmail.com" rel="" title="" class="quarto-navigation-tool px-1" aria-label=""><i class="bi bi-envelope"></i></a>
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#coeficiente-de-correlación" id="toc-coeficiente-de-correlación" class="nav-link active" data-scroll-target="#coeficiente-de-correlación">Coeficiente de correlación</a></li>
  <li><a href="#derribando-el-mito-del-r-0999" id="toc-derribando-el-mito-del-r-0999" class="nav-link" data-scroll-target="#derribando-el-mito-del-r-0999">Derribando el mito del r = 0,999…</a></li>
  <li><a href="#test-formales-de-linealidad" id="toc-test-formales-de-linealidad" class="nav-link" data-scroll-target="#test-formales-de-linealidad">Test formales de linealidad</a>
  <ul class="collapse">
  <li><a href="#test-de-carencia-de-ajuste-lack-of-fit-iso-11095" id="toc-test-de-carencia-de-ajuste-lack-of-fit-iso-11095" class="nav-link" data-scroll-target="#test-de-carencia-de-ajuste-lack-of-fit-iso-11095">Test de carencia de ajuste (<em>Lack of fit</em>) ISO 11095</a></li>
  <li><a href="#test-de-mandel-iso-8466-1" id="toc-test-de-mandel-iso-8466-1" class="nav-link" data-scroll-target="#test-de-mandel-iso-8466-1">Test de Mandel ISO 8466-1</a></li>
  </ul></li>
  <li><a href="#entonces-resumiendo-por-qué-no-puedo-probar-linealidad-de-la-curva-de-calibración" id="toc-entonces-resumiendo-por-qué-no-puedo-probar-linealidad-de-la-curva-de-calibración" class="nav-link" data-scroll-target="#entonces-resumiendo-por-qué-no-puedo-probar-linealidad-de-la-curva-de-calibración">Entonces, resumiendo ¿Por qué no puedo probar linealidad de la curva de calibración?</a></li>
  <li><a href="#en-defensa-del-coeficiente-de-correlación" id="toc-en-defensa-del-coeficiente-de-correlación" class="nav-link" data-scroll-target="#en-defensa-del-coeficiente-de-correlación">En defensa del coeficiente de correlación</a></li>
  <li><a href="#por-último-y-el-r2" id="toc-por-último-y-el-r2" class="nav-link" data-scroll-target="#por-último-y-el-r2">Por último… ¿y el <span class="math inline">\(r^2\)</span>?</a></li>
  <li><a href="#bibliografía" id="toc-bibliografía" class="nav-link" data-scroll-target="#bibliografía">Bibliografía</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">¿Cómo demuestro que mi curva de calibración es lineal?</h1>
</div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">August 23, 2017</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<p>En este post intentaremos derribar el mito del coeficiente de correlación con “muchos” 9’s como prueba de linealidad. Además, presentaremos dos test formales para evaluar el modelo de calibración lineal en química analítica.</p>
<section id="coeficiente-de-correlación" class="level1">
<h1>Coeficiente de correlación</h1>
<p>Este parámetro estadístico indica la fuerza y dirección de la relación de dos variables cuantitativas, por ejemplo;</p>
<ul>
<li>Concentración (<span class="math inline">\(x\)</span>) y Absorbancia (<span class="math inline">\(y\)</span>)</li>
<li><span class="math inline">\(log \text{ Concentración}\)</span> y <span class="math inline">\(E\)</span> Potencial (Ecuación de Nernst)</li>
<li>La edad de las ganadoras de Miss América con los asesinatos utilizando objetos calientes y vapor. ¡Cuidado con las correlaciones <a href="http://tylervigen.com/spurious-correlations">espurias</a>!</li>
</ul>
<p>Todos los químicos estamos familiarizados con la ecuación de Lambert-Beer, la cual establece la archiconocida relación entre absorbancia y concentración en métodos espectrofotométricos:</p>
<p><span class="math display">\[\begin{equation}
  \underbrace{A}_\text{y} = \underbrace{\epsilon \cdot b}_\text{$\beta_{1}$} \cdot
  \underbrace{C}_\text{x}
    (\#eq:lambert)
\end{equation}\]</span></p>
<p>De la ecuación @ref(eq:lambert) se observa claramente la relación con el modelo estándar de calibración lineal <span class="math inline">\(y = \beta_{0} + \beta_{1}x\)</span> asumiendo un intercepto <span class="math inline">\(\beta_{0} = 0\)</span>. Por lo tanto ¿por qué nos sorprende tanto encontrar un coeficiente de correlación alto en curvas de calibración espectrofotométricas? Era totalmente esperable, pues hay un modelo físico-químico que sustenta el modelo lineal.</p>
<p>OK, de acuerdo. Este modelo físico-químico sólo es válido bajo ciertas condiciones (como todos los modelos), de hecho son conocidas las desviaciones de la ley de Lambert-Beer a altas concentraciones.</p>
</section>
<section id="derribando-el-mito-del-r-0999" class="level1">
<h1>Derribando el mito del r = 0,999…</h1>
<p>Para comenzar, por favor, ponga atención a la figura @ref(fig:anscombe) denominada “El Cuarteto de Anscombe”. La “gracia” de estos datos de calibración es que todos tienen la misma pendiente, intercepto, error de calibración y… ¡coeficiente de correlación!</p>
<p>¿No me cree? Le dejo este <a href="https://1drv.ms/x/s!AuF6FPVWruwDyKxMLQ2ngb99Eo3q7w?e=5jIW6e">link</a> para que descargue los datos en archivo Excel y se convenza con sus propios ojos.</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/anscombe-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">El Cuarteto de Ascombe</figcaption>
</figure>
</div>
</div>
</div>
<p>El punto que revela la figura @ref(fig:anscombe) es que es posible obtener coeficientes de correlación “altos” inclusive con datos que, a simpe vista, no revelan una relación lineal entre <span class="math inline">\(X\)</span> e <span class="math inline">\(Y\)</span>. Es más, es posible obtener un alto coeficiente de correlación donde no existe absolutamente ninguna correlación entre <span class="math inline">\(X\)</span> e <span class="math inline">\(Y\)</span> mediante un mal de diseño de la curva de calibración. Por ejemplo, en la figura @ref(fig:influyente) se muestra a la izquierda que la correlación entre <span class="math inline">\(x\)</span> e <span class="math inline">\(y\)</span> es prácticamente 0. Sin embargo, cuando incluimos un punto <em>influyente</em>, muy alejado de la nube de puntos a baja concentración, mágicamente el r = 1 (derecha).</p>
<blockquote class="blockquote">
<p><em>Moraleja:</em> Trate, en lo posible, de diseñar la curva con los puntos equiespaciados y evite los saltos de varios órdenes de magnitud de la concentración.</p>
</blockquote>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/influyente-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Punto inlfuyente en la calibración</figcaption>
</figure>
</div>
</div>
</div>
<p>La linealidad tampoco es un parámetro cuantitativo, una curva con r = 0,999 no es más lineal que otra con r = 0,99. Observe la figura @ref(fig:simplot), ambas curvas fueron simuladas en lenguaje <code>R</code> con el mismo intercepto y pendiente siguiendo estrictamente el modelo lineal <span class="math inline">\(y = \beta_{0} + \beta_{1}x\)</span>, sin embargo, tienen coeficientes de correlación distintos. La curva de la izquierda no es más lineal que la de la derecha ya que ambas fueron simuladas a partir del mismo modelo, la única diferencia es que la de la derecha tiene una mayor dispersión de los puntos, pero no por ello es “menos lineal”, de hecho ambas lo son, pues fueron simuladas.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>) <span class="co"># Es para que Ud. obtenga los mismos </span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>              <span class="co"># resultados en su simulación en R</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>              </span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>b0 <span class="ot">&lt;-</span> <span class="dv">1</span>  <span class="co"># Intercepto = 1</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>b1 <span class="ot">&lt;-</span> <span class="dv">10</span> <span class="co"># Pendiente = 10</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>s <span class="ot">&lt;-</span> <span class="dv">1</span>   <span class="co"># Desviación estándar de calibración</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Simulamos el mismo modelo lineal </span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">10</span> <span class="co"># Calibrantes</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>y1 <span class="ot">&lt;-</span> b0 <span class="sc">+</span> b1<span class="sc">*</span>x <span class="sc">+</span> <span class="fu">rnorm</span>(<span class="dv">10</span>, <span class="dv">0</span>, s) <span class="co"># Absorbancias con </span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>                                  <span class="co"># error = s = 1</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>y2 <span class="ot">&lt;-</span> b0 <span class="sc">+</span> b1<span class="sc">*</span>x <span class="sc">+</span> <span class="fu">rnorm</span>(<span class="dv">10</span>, <span class="dv">0</span>, <span class="dv">10</span><span class="sc">*</span>s) <span class="co"># Absorbancias con </span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>                                     <span class="co"># error = 10*s = 10</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/simplot-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Simulación de curvas perfectamente lineales</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="test-formales-de-linealidad" class="level1">
<h1>Test formales de linealidad</h1>
<p>Existen varios tests estadísticos formales para evaluar el supuesto de linealidad de la curva de calibración. Sin embargo, en este post veremos dos que son los más utilizados en Química Analítica y son sugeridos por normativas internacionales (para presentárselos a los amables auditores).</p>
<p>Si bien no es estrictamente riguroso, para simplificar el concepto, diremos que ambos tests estadísticos intentan dirimir entre dos hipótesis:</p>
<ul>
<li><span class="math inline">\(H_{0}\)</span> (a.k.a Hipótesis Nula) : El modelo lineal es adecuado para describir los datos de calibración</li>
<li><span class="math inline">\(H_{1}\)</span> (a.k.a Hipótesis alternativa): El modelo lineal <strong>NO</strong> es adecuado para describir los datos de calibración</li>
</ul>
<p>También debemos hacer la siguiente acotación: En <strong>estadística</strong> un modelo lineal es aquel en que sus parámetros son lineales. Por ejemplo, la curva de calibración lineal clásica <span class="math inline">\(y = \beta_{0} + \beta_{1}x\)</span> tanto <span class="math inline">\(\beta_{0}\)</span> y <span class="math inline">\(\beta_{1}\)</span> son lineales. Sin embargo, en un modelo exponencial <span class="math inline">\(y = \gamma_{0} e^{\gamma_{1}x}\)</span> el coeficiente <span class="math inline">\(\gamma_{1}\)</span> no lo es.</p>
<p>Dicho esto, el modelo cuadrático de calibración <span class="math inline">\(y = \beta_{0} + \beta_{1}x + \beta_{2}x^2\)</span> <strong>es lineal</strong> desde el punto de vista estrictamente estadístico. Sin embargo, debido al arraigo del concepto de linealidad en química analítica no modificaremos su interpretación.</p>
<section id="test-de-carencia-de-ajuste-lack-of-fit-iso-11095" class="level2">
<h2 class="anchored" data-anchor-id="test-de-carencia-de-ajuste-lack-of-fit-iso-11095">Test de carencia de ajuste (<em>Lack of fit</em>) ISO 11095</h2>
<p>Este test está basado en comparar dos estimadores del error aleatorio:</p>
<ol type="1">
<li>Error puro o experimental</li>
<li>Error de carencia de ajuste o <em>lack of fit</em></li>
</ol>
<p>Es decir, necesitamos un estimador del error aleatorio totalmente independiente del error del modelo de calibración que queremos ajustar. Para estimar este error, la prueba de carencia de ajuste exige que hagamos replicados de cada uno de los calibrantes.</p>
<blockquote class="blockquote">
<p>Pero tienen que ser replicados verdaderos. No es válido inyectar varias veces el mismo estándar en el equipo. Prepárelos independientemente.</p>
</blockquote>
<p>Si los dos estimadores del error aleatorio son similares, entonces el modelo de calibración que acabamos de ajustar es adecuado para modelar los datos experimentales. ¿Cuán similares tienen que ser? Lo probaremos con un test F. Los detalles algebraicos son latosos-engorrosos y pueden ser consultados en la bibliografía. Sólo indicaremos cómo hacer este test de linealidad en lenguaje <code>R</code>, como no. (¿Y en Excel cuándo?)</p>
<p>La tabla @ref(tab:lof) muestra los datos de calibración de cloranfenicol en matriz leche obtenida por GC/MS-NCI (<em>Gas Chromatography/Mass Spectrometry - Negative Chemical Ionization</em> …¡Qué tiempos aquellos!). Note que cada nivel de calibración está preparado en triplicado totalizando n = 15 calibrantes independientes. La figura @ref(fig:lofplot) muestra la curva de calibración.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small" data-quarto-postprocess="true">
<caption>Calibración CAF [ug/kg]</caption>
<thead>
<tr class="header">
<th style="text-align: center;" data-quarto-table-cell-role="th">Replicado</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">0</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">0.25</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">0.5</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">0.75</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">1</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">1</td>
<td style="text-align: center;">88</td>
<td style="text-align: center;">7714</td>
<td style="text-align: center;">15292</td>
<td style="text-align: center;">22611</td>
<td style="text-align: center;">30280</td>
</tr>
<tr class="even">
<td style="text-align: center;">2</td>
<td style="text-align: center;">154</td>
<td style="text-align: center;">7726</td>
<td style="text-align: center;">14947</td>
<td style="text-align: center;">22945</td>
<td style="text-align: center;">30222</td>
</tr>
<tr class="odd">
<td style="text-align: center;">3</td>
<td style="text-align: center;">512</td>
<td style="text-align: center;">8043</td>
<td style="text-align: center;">15063</td>
<td style="text-align: center;">22772</td>
<td style="text-align: center;">30089</td>
</tr>
</tbody>
</table>


</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/lofplot-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Curva de calibración CAF. Test de carencia de ajuste</figcaption>
</figure>
</div>
</div>
</div>
<p>La tabla @ref(tab:lofcal) muestra el análisis estadístico de esta calibración:</p>
<!-- Ancho de las tabla -->

<style type="text/css">
.table {

    width: 100%;
    
}
</style>
<div class="cell">
<div class="cell-output-display">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<caption>Pendiente e intercepto de calibración</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">term</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">estimate</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">std.error</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">statistic</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">262</td>
<td style="text-align: right;">78</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0.005</td>
</tr>
<tr class="even">
<td style="text-align: left;">x.caf</td>
<td style="text-align: right;">29936</td>
<td style="text-align: right;">127</td>
<td style="text-align: right;">236</td>
<td style="text-align: right;">0.000</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>Por ahora no nos detendremos en el análisis de la tabla (eso quedará para otro post). Haremos directamente el Test de Carencia de Ajuste (<em>lack of fit</em>) en <code>R</code> el cual se muestra en la tabla @ref(tab:loftest):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(olsrr) <span class="co"># Cargamos el package 'olsrr' para aplicar el test lack-of-fit</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ols_pure_error_anova</span>(fit.cal)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Lack of Fit F Test 
------------------
Response :   y.caf 
Predictor:   x.caf 

                           Analysis of Variance Table                             
---------------------------------------------------------------------------------
                DF       Sum Sq           Mean Sq        F Value        Pr(&gt;F)    
---------------------------------------------------------------------------------
x.caf            1    1680303154.42    1680303154.42     54131.47    6.444664e-25 
Residual        13        392485.57         30191.20                              
 Lack of fit     3         82074.03         27358.01    0.8813464       0.4832262 
 Pure Error     10        310411.54         31041.15                              
---------------------------------------------------------------------------------</code></pre>
</div>
</div>
<p>Ok, para interpretar el test de carencia de ajuste nos fijaremos en la fila que dice “<em>Lack of fit</em>” y en el <em>p-value</em> del test, el cual aparece bajo la columna <em>Pr(&gt;F)</em> = 0.483. La interpretación tradicional de una prueba estadística diría algo más o menos así:</p>
<blockquote class="blockquote">
<p>Dado que el <em>p-value</em> <span class="math inline">\(&gt; 0.05\)</span>, entonces, no hay evidencias en contra de la hipótesis nula. El modelo lineal es adecuado para modelar los datos de calibración.</p>
</blockquote>
<p>Algunas consideraciones:</p>
<ol type="1">
<li>¿Dice en alguna parte que el modelo de calibración es lineal? Póngalo de <em>wallpaper</em> en su pantalla: <strong>NO</strong>.</li>
<li>Lo único que se puede extraer como conclusión es que el modelo lineal es adecuado, es razonable para modelar los datos de calibración. Nada más.</li>
<li>Existen infinitos modelos de calibración que podrían ser idóneos, este test nos dice si el que hemos elegido para modelar los datos es razonable/adecuado, sin embargo, no nos dice que sea “EL” modelo perfecto.</li>
<li>¿Qué tiene de especial el famoso 0,05? Absolutamente <em>NADA</em>. ¿Qué concluiría Ud. si el <em>p-value</em> fuese 0,04999 ó 0,05001? Sería un test totalmente inconcluyente.</li>
<li>Lamentablemente, esto es una dicotomía perversa que desde hace mucho tiempo ha sido objeto de varias críticas. Le invito a leer las siguientes referencias sobre la interpretación y controversia de los <em>p-values</em> en ciencia:</li>
</ol>
<ul>
<li><p>Ronald L. Wasserstein &amp; Nicole A. Lazar (2016) The ASA’s Statement on p-Values: Context, Process, and Purpose <em>The American Statistician Volume 70, 2016 - Issue 2</em> <a href="http://amstat.tandfonline.com/doi/abs/10.1080/00031305.2016.1154108">link</a></p></li>
<li><p>M.Baker Statisticians issue warning over misuse of P values <em>Nature <strong>531</strong>, 151 (10 March 2016)</em> <a href="http://www.nature.com/news/statisticians-issue-warning-over-misuse-of-p-values-1.19503">link</a></p></li>
<li><p>Singh Chawla D. Big names in statistics want to shake up much-maligned P value. <em>Nature. 2017 Jul 26;548(7665):16-17</em> <a href="https://www.nature.com/news/big-names-in-statistics-want-to-shake-up-much-maligned-p-value-1.22375?beta=false">link</a></p></li>
</ul>
<blockquote class="blockquote">
<p>“The p-value was never intended to be a substitute for scientific reasoning” Ron Wasserstein, Director Ejecutivo de la Asociación Americana de Estadística ASA.</p>
</blockquote>
</section>
<section id="test-de-mandel-iso-8466-1" class="level2">
<h2 class="anchored" data-anchor-id="test-de-mandel-iso-8466-1">Test de Mandel ISO 8466-1</h2>
<p>Esta prueba estadística es bastante sencilla y está basada en la comparación entre el modelo de calibración lineal y un modelo alternativo. Por lo tanto, no es una prueba absoluta, sino relativa a la elección del modelo alternativo. Require al menos n = 6 calibrantes (sin replicado).</p>
<p>En general, el test de Mandel utiliza el modelo de calibración cuadrático para compararlo con el modelo lineal:</p>
<p><span class="math display">\[ y = \beta_{0} + \beta_{1}x + \beta_{2}x^2\]</span></p>
<p>Los detalles estadísticos pueden consultarse en la bibliografía.</p>
<ol type="1">
<li>Primero calcule la suma de cuadrados de los residuos <span class="math inline">\(SS_{r}\)</span> para cada uno de los modelos de acuerdo a la siguiente expresión:</li>
</ol>
<p><span class="math display">\[\begin{equation}
  SS_{r} = \sum_{i = 1}^{n} e_{i}^2
    (\#eq:res)
\end{equation}\]</span></p>
<p>Donde el residuo <span class="math inline">\(e = y - \hat{y}\)</span>. <span class="math inline">\(y\)</span> es la respuesta instrumental observada o experimental (áreas, absorbancias, etc.); <span class="math inline">\(\hat{y}\)</span>, es la respuesta instrumental que predice el modelo (lineal o o cuadrático) en cada una de las concentraciones de los calibrantes. Si observa la ecuación @ref(eq:res) el concepto de residuo es el mismo para cualquier modelo de calibración, es decir, ¿cuánto difiere lo que se observa experimentalmente con lo que predice el modelo?</p>
<p>Un buen modelo tiene residuos pequeños. Un residuo grande para cierto de nivel de concentración implica que existe una gran diferencia entre lo observado y lo que predice el modelo, por lo tanto, nos guiará (en otro post) a detectar posibles valores anómalos o <em>outliers</em>.</p>
<ol start="2" type="1">
<li>Calcule la diferencia entre ambas sumas de cuadrado de los residuos, la del modelo no lineal <span class="math inline">\(SS_{r}^{no-lin}\)</span> y la correspondiente al modelo lineal <span class="math inline">\(SS_{r}^{lin}\)</span>:</li>
</ol>
<p><span class="math display">\[\begin{equation}
  D = SS_{r}^{no-lin} -  SS_{r}^{lin}
  (\#eq:D)
\end{equation}\]</span></p>
<ol start="3" type="1">
<li>Estime el estadístico F calculado:</li>
</ol>
<p><span class="math display">\[\begin{equation}
  F = \frac{D}{SS_{r}^{no-lin}/(n - 3)}
  (\#eq:D)
\end{equation}\]</span></p>
<ol start="3" type="1">
<li><p>Obtenga el F de tabla para 1 grado de libertad en el numerador y <span class="math inline">\(n - 3\)</span> para el denominador</p></li>
<li><p>Compare el <span class="math inline">\(F_{calculado}\)</span> con el <span class="math inline">\(F_{tabla}\)</span> y decida en base a la siguiente regla:</p></li>
</ol>
<ul>
<li><p>Si <span class="math inline">\(F_{calculado} &lt; F_{tabla}\)</span> se concluye que no hay evidencias en contra de la hipótesis nula de linealidad del modelo. ¿Quiere decir que el modelo de calibración es exactamente lineal? Ya sabemos que <strong>NO</strong>. Rigen las mismas consideraciones que que notamos en el test de carencia de ajuste.</p></li>
<li><p>Si <span class="math inline">\(F_{calculado} &gt; F_{tabla}\)</span> se rechaza la hipótesis nula de linealidad del modelo. Los datos no son consistentes con la hipótesis. Y aquí se abre una caja de Pandora, pues esta conclusión también tiene muchas consideraciones estadísticas que se deben tener en cuenta para interpretarla apropiadamente las cuales, por ahora, no profundizaremos.</p></li>
</ul>
<p>Los pasos recién descritos son para llevar a cabo el Test de Mandel “a mano”, afortunadamente los softwares estadísticos como <code>R</code> y Excel (sí ¡Excel!) tienen incorporada esta prueba estadística de linealidad. Veamos un ejemplo.</p>
<p>La tabla @ref(tab:datamandel) muestra los datos de calibración de Cu por AAS; la figura @ref(fig:plotmandel), la curva de calibración:</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small" data-quarto-postprocess="true">
<caption>Curva de Calibración Cu</caption>
<thead>
<tr class="header">
<th style="text-align: center;" data-quarto-table-cell-role="th">0</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">10</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">20</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">30</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">40</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">50</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">60</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">70</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">80</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">90</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">100</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">-0.007</td>
<td style="text-align: center;">0.071</td>
<td style="text-align: center;">0.146</td>
<td style="text-align: center;">0.212</td>
<td style="text-align: center;">0.274</td>
<td style="text-align: center;">0.334</td>
<td style="text-align: center;">0.385</td>
<td style="text-align: center;">0.43</td>
<td style="text-align: center;">0.473</td>
<td style="text-align: center;">0.511</td>
<td style="text-align: center;">0.546</td>
</tr>
</tbody>
</table>


</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/plotmandel-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Curva de calibración Cu</figcaption>
</figure>
</div>
</div>
</div>
<p>A simple vista se observa la no linealidad de la curva de calibración. Veamos que nos dice el Test de Mandel en la siguiente tabla ANOVA:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># d: corresponde al data frame de los datos de calibración</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>fit.lin <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> x, <span class="at">data =</span> d) <span class="co"># Ajuste lineal.</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>fit.nolin <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> x <span class="sc">+</span> <span class="fu">I</span>(x<span class="sc">^</span><span class="dv">2</span>), <span class="at">data =</span> d) <span class="co"># Ajuste no lineal cuadrático</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(fit.lin, fit.nolin)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: y ~ x
Model 2: y ~ x + I(x^2)
  Res.Df       RSS Df Sum of Sq      F    Pr(&gt;F)    
1      9 0.0054816                                  
2      8 0.0000186  1  0.005463 2351.1 3.621e-11 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>En la tabla el valor <span class="math inline">\(F = 2351\)</span> corresponde al <span class="math inline">\(F_{calculado}\)</span> el cual es comparado internamente con el <span class="math inline">\(F_{tabla}\)</span> entregando, finalmente, el <em>p-value</em> <span class="math inline">\(Pr(&gt;F) = 3.62e-11\)</span>. La evidencia en contra de la hipótesis nula de linealidad es abrumadora.</p>
</section>
</section>
<section id="entonces-resumiendo-por-qué-no-puedo-probar-linealidad-de-la-curva-de-calibración" class="level1">
<h1>Entonces, resumiendo ¿Por qué no puedo probar linealidad de la curva de calibración?</h1>
<p>Porque la decisión está basada en pruebas estadísticas, las cuáles tienen algunas consideraciones para su correcta interpretación:</p>
<ol type="1">
<li><p>Con estas pruebas estadísticas no se puede probar linealidad, lo que podemos concluir es que el modelo lineal es adecuado o razonable para modelar nuestros datos de calibración ¡nada más!.</p></li>
<li><p>Es imposible que en un sistema físico-químico complejo como una llama o plasma/detector (ICP-MS) exista una relación “perfectamente” lineal entre absorbancia (cuentas) y concentración. Lo que hicieron Lambert &amp; Beer (o cualquier científico que proponga un modelo de la naturaleza) fue proponer una simplificación del sistema y representarlo mediante un modelo cuantitativo.</p></li>
<li><p>Existen muchos modelos que se podrían ajustar muy bien a nuestros datos de calibración, pero en estadística existe el principio de parsimonia:</p></li>
</ol>
<blockquote class="blockquote">
<p>En igualdad de condiciones, la explicación más sencilla suele ser la más probable</p>
</blockquote>
<p>¿Por qué complicarnos la existencia con un modelo hiper-super-parabólico- tangencial si el modelo lineal es razonable y adecuado para nuestros propósitos de cuantificación? Pero ojo:</p>
<blockquote class="blockquote">
<p>“Everything should be made as simple as possible, but no simpler” – Albert Einstein</p>
</blockquote>
<p>Es aquí donde las pruebas estadísticas nos ayudan a decidir entre varios modelos plausibles.</p>
</section>
<section id="en-defensa-del-coeficiente-de-correlación" class="level1">
<h1>En defensa del coeficiente de correlación</h1>
<p>Es cierto, el <span class="math inline">\(r\)</span> con “muchos” 9’s no es una prueba formal de linealidad… ¿quiere decir que el <span class="math inline">\(r\)</span> no es importante en Química Analítica? Por supuesto que sí lo es. Anote:</p>
<blockquote class="blockquote">
<p>El coeficiente de correlación está íntimamente ligado con la incertidumbre de calibración. A mayor <span class="math inline">\(r\)</span> menor es la incertidumbre de calibración.</p>
</blockquote>
<p>Puede profundizar en este aspecto consultando en:</p>
<p>Ellison, S.L.R. In defense of the correlation coefficient. <em>Accred Qual Assur (2006) 11: 146.</em> https://doi.org/10.1007/s00769-006-0087-y</p>
</section>
<section id="por-último-y-el-r2" class="level1">
<h1>Por último… ¿y el <span class="math inline">\(r^2\)</span>?</h1>
<p>Ahhh, pero eso es otra cosa… hasta la próxima.</p>
</section>
<section id="bibliografía" class="level1">
<h1>Bibliografía</h1>
<ol type="1">
<li><p>Lutz Brüggemann, Wolfgang Quapp, Rainer Wennrich <strong>Test for non-linearity concerning linear calibrated chemical measurements</strong> (2006) <em>Accreditation and Quality Assurance Volume 11, Issue 12, pp 625–631</em></p></li>
<li><p>J. M. Andrade and M. P. Gómez-Carracedo <strong>Notes on the use of Mandel’s test to check for nonlinearity in laboratory calibrations</strong> <em>Anal. Methods, 2013,5, 1145-1149</em></p></li>
</ol>
<hr>


</section>

<a onclick="window.scrollTo(0, 0); return false;" role="button" id="quarto-back-to-top"><i class="bi bi-arrow-up"></i> Back to top</a></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">Copyright 2024, Carlos Gómez</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/analytical/website_analytical">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/cjgomezs/">
      <i class="bi bi-linkedin" role="img">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>



</body></html>